export const dom = {
  boardElement: document.getElementById("board"),
  scoreElement: document.getElementById("score"),
  restartBtn: document.getElementById("restartBtn"),
  gameContainer: document.getElementById("gameContainer"),
  canvas: document.getElementById("lineCanvas"),
  ctx: document.getElementById("lineCanvas").getContext("2d"),

  startScreen: document.getElementById("startScreen"),
  endScreen: document.getElementById("endScreen"),
  endMessage: document.getElementById("endMessage"),
  bonusMessage: document.getElementById("bonusMessage"),
  modeBonusMessage: document.getElementById("modeBonusMessage"),
  totalScoreMessage: document.getElementById("totalScoreMessage"),
  leaderboardRankMessage: document.getElementById("leaderboardRankMessage"),

  hintBtn: document.getElementById("hintBtn"),
  homeBtn: document.getElementById("homeBtn"),
  soundBtn: document.getElementById("soundBtn"),
  reshuffleBtn: document.getElementById("reshuffleBtn"),
  pauseBtn: document.getElementById("pauseBtn"),
  endRunBtn: document.getElementById("endRunBtn"),

  timeBar: document.getElementById("timeBar"),
  timeBarValue: document.getElementById("timeBarValue"),
  leaderboardBody: document.getElementById("leaderboardBody"),
  pauseOverlay: document.getElementById("pauseOverlay"),
  quitConfirmOverlay: document.getElementById("quitConfirmOverlay"),
  quitConfirmText: document.getElementById("quitConfirmText"),
  confirmQuitBtn: document.getElementById("confirmQuitBtn"),
  cancelQuitBtn: document.getElementById("cancelQuitBtn"),
  boardWrapper: document.querySelector(".board-wrapper"),

  timeColumn: document.querySelector(".time-column"),
  timeTrack: document.querySelector(".time-track"),
  timeTitle: document.querySelector(".time-column-title"),

  playTypeDescription: document.getElementById("playTypeDescription"),
  singleRunBtn: document.getElementById("singleRunBtn"),
  continuousRunBtn: document.getElementById("continuousRunBtn"),
  offlineBackToModeSelectBtn: document.getElementById("offlineBackToModeSelectBtn"),
  backToPvpLobbyBtn: document.getElementById("backToPvpLobbyBtn"),
  backToOfflineScreenBtn: document.getElementById("backToOfflineScreenBtn"),

  toastContainer: document.getElementById("toastContainer"),
  volumeSlider: document.getElementById("volumeSlider"),

  modeSelectScreen: document.getElementById("modeSelectScreen"),
  offlineEntryBtn: document.getElementById("offlineEntryBtn"),
  pvpEntryBtn: document.getElementById("pvpEntryBtn"),

  authScreen: document.getElementById("authScreen"),
  authTitle: document.getElementById("authTitle"),
  authPlayerNameInput: document.getElementById("authPlayerNameInput"),
  pirateFactionBtn: document.getElementById("pirateFactionBtn"),
  marineFactionBtn: document.getElementById("marineFactionBtn"),
  signUpBtn: document.getElementById("signUpBtn"),
  signInBtn: document.getElementById("signInBtn"),
  authBackBtn: document.getElementById("authBackBtn"),
  pvpLobbyBackBtn: document.getElementById("pvpLobbyBackBtn"),

  pvpLobbyScreen: document.getElementById("pvpLobbyScreen"),
  pvpWelcomeText: document.getElementById("pvpWelcomeText"),
  pvpProfileText: document.getElementById("pvpProfileText"),
  pvpTop10Body: document.getElementById("pvpTop10Body"),
  pvpRoomTitle: document.getElementById("pvpRoomTitle"),

  practiceBotBtn: document.getElementById("practiceBotBtn"),
  friendlyPvpBtn: document.getElementById("friendlyPvpBtn"),
  rankedPvpBtn: document.getElementById("rankedPvpBtn"),

  pvpRoomCard: document.getElementById("pvpRoomCard"),
  createRoomBtn: document.getElementById("createRoomBtn"),
  joinRoomBtn: document.getElementById("joinRoomBtn"),
  roomCodeInput: document.getElementById("roomCodeInput"),
  roomStatusText: document.getElementById("roomStatusText"),

  myProfileHistoryBtn: document.getElementById("myProfileHistoryBtn"),
  profileHistoryModal: document.getElementById("profileHistoryModal"),
  profileHistoryTitle: document.getElementById("profileHistoryTitle"),
  profileHistoryMeta: document.getElementById("profileHistoryMeta"),
  profileHistoryPrivacyWrap: document.getElementById("profileHistoryPrivacyWrap"),
  profileHistoryVisibilityToggle: document.getElementById("profileHistoryVisibilityToggle"),
  profileHistoryStats: document.getElementById("profileHistoryStats"),
  profileHistoryList: document.getElementById("profileHistoryList"),
  closeProfileHistoryBtn: document.getElementById("closeProfileHistoryBtn"),

  playerSearchInput: document.getElementById("playerSearchInput"),
  playerSearchBtn: document.getElementById("playerSearchBtn"),
  playerSearchStatus: document.getElementById("playerSearchStatus"),
  playerSearchResultsBody: document.getElementById("playerSearchResultsBody"),

  friendsListWrap: document.getElementById("friendsListWrap"),
  friendRequestsWrap: document.getElementById("friendRequestsWrap"),
  randomFriendlyMatchBtn: document.getElementById("randomFriendlyMatchBtn"),
  cancelRandomFriendlyMatchBtn: document.getElementById("cancelRandomFriendlyMatchBtn"),

  rankedCreateRoomBtn: document.getElementById("rankedCreateRoomBtn"),
  rankedJoinRoomBtn: document.getElementById("rankedJoinRoomBtn"),
  rankedRandomMatchBtn: document.getElementById("rankedRandomMatchBtn"),
  rankedRoomCode: document.getElementById("rankedRoomCode"),

  matchInvitesWrap: document.getElementById("matchInvitesWrap")
};